# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.2.0.7-fabric+mc26.1.2
maven_group=com.github.ysbbbbbb.kaleidoscopetavern
archives_base_name=kaleidoscope_tavern

# Dependencies
fabric_api_version=0.155.3+26.1.2
jade_version=26.1.6+fabric
rrv_version=8.4.0+26.1.2-fabric
jei_version=26.1.2-fabric:29.16.0.47
rei_version=26.1.819
forge_config_api_version=26.1.5
trinkets_version=4.0.0-beta.3+26.1
create_version=26.1.2-6.0.9-4
